### ISSUE TITLE
wpf that would trigger a web request

### ISSUE THREAD

**Issue by benton932** [Michael-Zp/Aoe2DESpecChat#2]

**Comment by benton932** [comment]
oh, that suggestion doesn't help.

**Comment by Michael-Zp** [comment]
Hey, thanks for reaching out, but sadly the <local:Age2Hyperlink NavigateUri=...> is what I already played around with and I didn't get it to work, because I couldn't dynamically change the hyperlink (which is needed if you want to alter the URL for each chat message that you want to send as a REST request).
